# An app config, provided by App: http://github.com/stephencelis/app
---
development: &development
  loaded_at: <%= Time.zone.now.iso8601 %>
  downloads:
      movies: /Users/hornairs/Code/scurvy-test/movies
      music: /Users/hornairs/Code/scurvy-test/music
  apis:
      lastfm: "cc85b6d4313e40450230872430b4d631"
test:
  <<: *development

production:
  loaded_at: <%= Time.zone.now.iso8601 %>
  downloads:
      movies: /var/downloads/movies
      music: /var/downloads/music
  apis:
      lastfm: "cc85b6d4313e40450230872430b4d631"