class CreateTracks < ActiveRecord::Migration
  def self.up
    create_table :tracks do |t|
      t.string :name, :null => false
      t.integer :artist_id, :null => false
      t.integer :album_id, :null => false
      t.integer :lastfm_id
      t.string :mb_id
      t.integer :duration
      t.string :bitrate
      t.string :url
      t.integer :listeners
      t.integer :position
      t.boolean  :autogenerated, :null => false
      
      t.timestamps
    end
  end

  def self.down
    drop_table :tracks
  end
end
