class CreateAlbums < ActiveRecord::Migration
  def self.up
    create_table :albums do |t|
      t.string :name, :null => false
      t.string :url
      t.integer :lastfm_id
      t.string :mb_id
      t.string :image_url
      t.integer :artist_id
      t.date :release_date
      t.integer :listeners
      t.boolean  :autogenerated, :null => false
      
      t.timestamps
    end
  end

  def self.down
    drop_table :albums
  end
end
