class CreateArtists < ActiveRecord::Migration
  def self.up
    create_table :artists do |t|
      t.string :name, :null => false
      t.string :url
      t.integer :listeners
      t.string :mb_id
      t.string :image_url
      t.boolean  :autogenerated, :null => false
      
      t.timestamps
    end
  end

  def self.down
    drop_table :artists
  end
end
