class Movie < ActiveRecord::Base
  has_one :download, :as => :resource
  
  validates_presence_of :title
  validates_numericality_of :year, :allow_nil => true
  validates_numericality_of :imdbid, :allow_nil => true
  validates_numericality_of :imdbrating, :allow_nil => true
  validates_url_format_of :posterurl, :allow_nil => true
  
  validates_inclusion_of :autogenerated, :in => [true, false]
  
  def self.per_page
    15
  end  
end
